[[redirects]]
  from = "/funds/:fund"
  to = "/funds/[fund].html?fund=:fund"
  status = 200

[[redirects]]
  from = "/funds/:fund/:asset"
  to = "/funds/[fund]/[asset].html?fund=:fund&asset=:asset"
  status = 200

[[redirects]]
  from = "/collections/:collection"
  to = "/collections/[collection].html?collection=:collection"
  status = 200
